TARGET = 'ocvFaceDetectApp'
APP_SOURCES = ['ocvFaceDetectApp.cpp']
ASSETS = ['haarcascade_eye.xml', 'haarcascade_frontalface_alt.xml']
DEBUG = 0

env = Environment()

# Cinder-OpenCV block
env = SConscript('../../../scons/SConscript', exports = ['env'])

env.Append(APP_SOURCES = APP_SOURCES)

SConscript('../../../../../scons/SConscript',
	exports = ['env', 'TARGET', 'ASSETS', 'DEBUG'])

