TARGET = 'ocvCaptureApp'
APP_SOURCES = ['ocvCaptureApp.cpp']
DEBUG = 0

env = Environment()

# Cinder-OpenCV block
env = SConscript('../../../scons/SConscript', exports = ['env'])

env.Append(APP_SOURCES = APP_SOURCES)

SConscript('../../../../../scons/SConscript',
	exports = ['env', 'TARGET', 'DEBUG'])

