CINDER_OPENCV_PATH = '../../../scons/'

import sys
sys.path.append(CINDER_OPENCV_PATH)
import CinderOpenCV
SOURCES = CinderOpenCV.getSources(CINDER_OPENCV_PATH)
INCLUDES = CinderOpenCV.getIncludes(CINDER_OPENCV_PATH)
LIBS = CinderOpenCV.getLibs(CINDER_OPENCV_PATH)
LIBS = [File(s) for s in LIBS]

TARGET = 'ocvOpticalFlowApp'
SOURCES += ['ocvOpticalFlowApp.cpp']
DEBUG = 0

SConscript('../../../../../scons/SConscript',
	exports = ['TARGET', 'SOURCES', 'INCLUDES', 'LIBS', 'DEBUG'])

