TARGET = 'ocvBasicApp'
APP_SOURCES = ['ocvBasicApp.cpp']
RESOURCES = ['dfw.jpg']
DEBUG = 0

env = Environment()

# Cinder-OpenCV block
env = SConscript('../../../scons/SConscript', exports = ['env'])

env.Append(APP_SOURCES = APP_SOURCES)

SConscript('../../../../../scons/SConscript',
	exports = ['env', 'TARGET', 'RESOURCES', 'DEBUG'])

