Import('env')

_INCLUDES = [Dir('../include').abspath]

if env['PLATFORM'] == 'darwin':
	_LIBS = ['libopencv_calib3d.a', 'libopencv_contrib.a',
				'libopencv_core.a', 'libopencv_features2d.a',
				'libopencv_flann.a', 'libopencv_gpu.a',
				'libopencv_haartraining_engine.a', 'libopencv_imgproc.a',
				'libopencv_legacy.a', 'libopencv_ml.a',
				'libopencv_objdetect.a', 'libopencv_video.a']
	_LIBS = [Dir('../lib/macosx/').abspath + '/' + s for s in _LIBS]
else:
	_LIBS = []

_LIBS = [File(s) for s in _LIBS]

env.Append(CPPPATH = _INCLUDES)
env.Append(LIBS = _LIBS)

Return('env')
